name: 'DSE_PG_BYPASS'

on:
  push:
    branches:
      - main

jobs:
  upload-release:
    runs-on: ubuntu-latest
    needs: [build_windows]
    steps:
    - uses: actions/checkout@v1
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.2
        release_name: DSE_PG_BYPASS-0.0.2
        draft: false
        prerelease: false
        
    - name: Download artifacts
      uses: actions/download-artifact@v1
      with:
        name: uploads 
        
    - name: Upload Windows artifact
      id: upload-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./uploads/DSE_PG_BYPASS-0.0.2-win64-release.zip
        asset_name: DSE_PG_BYPASS-0.0.2-win64-release.zip
        asset_content_type: application/zip
        
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
              
      - name: Set PATCH_VERSION
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -DPATCH_VERSION=2 ../
          
      - name: Running cmake
        shell: cmd
        run: |
          cd build
          cmake --build . --config Release
          
      - name: Create package
        shell: cmd
        run: |
          cd build
          cmake --build . --target package --config Release
          
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v1
        with:
          name: uploads
          path: ./build/DSE_PG_BYPASS-0.0.2-win64-release.zip